name: Run Tests

on:
    push:
        branches: [main, hien_dev]
    pull_request:
        branches: [main, hien_dev]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.11.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run tests
              run: |
                  pip install pytest
                  pytest tests/
