name: Run Tests

on:
    push:
        branches: [master, hien_dev]
    pull_request:
        branches: [master, hien_dev]

jobs:
    test-install-package:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.10.x, 3.11.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

                  pip install -r requirements.txt

                  python -c "import nltk; nltk.download('punkt_tab'); nltk.download('averaged_perceptron_tagger_eng')"

                  pip install pytest

            - name: Run pytest
              run: pytest tests/
